name: medfuse
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8
  - numpy>=1.20.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - scikit-learn>=1.0.0
  - scipy>=1.7.0
  - h5py>=3.1.0
  - opencv>=4.5.0
  - pillow>=9.0.0
  - notebook>=6.4.0
  - ipykernel>=6.0.0
  - ipython>=7.30.0
  - ipywidgets>=7.7.0
  - jupyter_client>=7.0.0
  - jupyter_core>=4.9.0
  - networkx>=2.6.0
  - requests>=2.27.0
  - tqdm>=4.62.0
  - pyyaml>=6.0
  - pip>=21.0.0
  - pip:
    - fuzzywuzzy>=0.18.0
    - warmup-scheduler==0.3
    - neptune-client>=1.0.0
    - numpy==1.24.3
    - seaborn